name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyautogui keyboard
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed human_typer.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: HumanTyper-Windows
        path: dist/human_typer.exe
        
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyautogui keyboard
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed human_typer.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: HumanTyper-MacOS
        path: dist/human_typer

